version: '3'

env:
  PYTHONPATH: "{PWD}:${PYTHONPATH}"

tasks:

  default:
    desc: help
    cmds:
      - task --list

  install:
    desc: Run setup.py to build the package.
    deps: [ make-venv ]
    cmds:
      - sudo {{.USER_WORKING_DIR}}/venv/bin/pip3 install --force-reinstall .

  install-dev:
    desc: Build the extension module in-place.
    deps: [ make-venv ]
    cmds:
      - ./venv/bin/pip3 install -e .

  test:
    desc: Run pytests.
    deps: [ install-dev, setup-network ]
    cmds:
      - sudo ip netns exec basic {{.USER_WORKING_DIR}}/venv/bin/python3 -m pytest {{.CLI_ARGS}}

  setup-network:
    desc: Setup the network namespaces for testing.
    cmds:
      - sudo ./network-setup.sh --overwrite

  build-docs:
    desc: Build the documentation.
    cmds:
      - sphinx-build -b html docs/ docs/_build/html

  make-venv:
    cmds:
      - python3 -m pip install virtualenv
      - python3 -m venv venv
      - ./venv/bin/pip3 install --upgrade setuptool wheel
    status:
      - '[ -d ./venv ]'
    preconditions:
      - sh: "which python3"
        msg: "You must have python3"