version: '3'

tasks:
  default:
    desc: help
    cmds:
      - task --list

  install:
    desc: Run setup.py to build the package.
    deps: [ make-venv ]
    cmds:
      - ./venv/bin/python3 setup.py sdist
      - sudo {{.USER_WORKING_DIR}}/venv/bin/pip3 install ./dist/pygmp-1.0.0.tar.gz --force-reinstall

  build-ext:
    desc: Build the extension module in-place.
    deps: [ make-venv ]
    cmds:
      - ./venv/bin/python3 setup.py build_ext --inplace --dry-run

  test:
    desc: Run pytests.
    deps: [ make-venv, build-ext ]
    cmds:
      - sudo ip netns exec basic {{.USER_WORKING_DIR}}/venv/bin/python3 -m pytest {{.CLI_ARGS}}

  setup-network:
    desc: Setup the network namespaces for testing.
    cmds:
      - sudo ./network-setup.sh --overwrite

  make-venv:
    cmds:
      - python3 -m pip install virtualenv
      - python3 -m venv venv
      - ./venv/bin/pip3 install setuptools wheel
    status:
      - '[ -d ./venv ]'
    preconditions:
      - sh: "which python3"
        msg: "You must have python3"