version: '3'

env:
  PYTHONPATH: "{PWD}:${PYTHONPATH}"

tasks:

  default:
    desc: help
    cmds:
      - task --list

  run:
    desc: Run the interactive shell.
    deps: [ install ]
    interactive: true
    cmds:
      - sudo ip netns exec basic {{.USER_WORKING_DIR}}/venv/bin/python3 pygmp interactive {{.CLI_ARGS}}

  install:
    desc: Build the extension in-place and install.  Adds metadata to venv lib linking source to pygmp directory.
    deps: [ make-venv ]
    cmds:
      - ./venv/bin/pip3 install -e .
    status:
      - '[ -n "$(find ./venv/lib/*/site-packages -type d -name "pygmp-*.dist-info" -print -quit)" ]'

  test:
    desc: Run pytests.
    deps: [ install, setup-network ]
    cmds:
      - sudo ip netns exec basic {{.USER_WORKING_DIR}}/venv/bin/python3 -m pytest {{.CLI_ARGS}}

  setup-network:
    desc: Setup the network namespaces for testing.
    cmds:
      - sudo ./network-setup.sh --overwrite

  build-docs:
    # FIXME: requires you activate the venv first
    desc: Build the documentation.
    cmds:
      - sphinx-build -E -b html docs/ docs/_build/html

  make-venv:
    cmds:
      - python3 -m pip install virtualenv
      - python3 -m venv venv
      - ./venv/bin/pip3 install --upgrade pip setuptools wheel
      - ./venv/bin/pip3 install -r dev-requirements.txt
    status:
      - '[ -d ./venv ]'
    preconditions:
      - sh: "which python3"
        msg: "You must have python3"